kind: Deployment
apiVersion: apps/v1
metadata:
  name: mi-sftp-server-test
  namespace: mi
  labels:
    app: mi-sftp-server-test
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mi-sftp-server-test
  template:
    metadata:
      labels:
        app: mi-sftp-server-test
        aadpodidbinding: mi-extraction-service
    spec:
      initContainers:
      - name: install
        image: busybox
        command: ["/bin/sh", "-c", "printf '%s:%s:1000::/files/mi-platform-export/' 'test-user' 'test-password' > /sftp-config/users.conf"]
        volumeMounts:
        - name: config-cache
          mountPath: /sftp-config
      containers:
        - name: mi-sftp-server-test
          image: atmoz/sftp:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: config-cache
            mountPath: /etc/sftp
          ports:
            - containerPort: 22
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
      volumes:
      - name: config-cache
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: mi-sftp-server-test-svc
  namespace: mi
spec:
  ports:
  - protocol: TCP
    port: 2000
    targetPort: 22
  selector:
    app: mi-sftp-server-test
